import os


PROXY_SERVER_URL = os.getenv("PROXY_SERVER_URL", "")
PROXY_API_KEY = os.getenv("PROXY_API_KEY", "")

ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'admin')


MONGO_HOST = os.getenv('MONGO_HOST', 'localhost')
MONGO_PORT = int(os.getenv('MONGO_PORT', '27017'))
MONGO_USERNAME = os.getenv('MONGO_USERNAME', '')
MONGO_PASSWORD = os.getenv('MONGO_PASSWORD', '')
MONGO_AUTH_SOURCE = os.getenv('MONGO_AUTH_SOURCE', 'admin')


MONGO_DB_NAME = os.getenv('MONGO_DB_NAME', 'xhs_demo')
MONGO_MEMBER_COLLECTION = 'member'
MONGO_DEVICE_COLLECTION = os.getenv('MONGO_DEVICE_COLLECTION', 'devices_demo')

MONGO_USER_ID_COLLECTION = os.getenv('MONGO_USER_ID_COLLECTION', 'userid')
MONGO_SEND_TEXT_COLLECTION = os.getenv('MONGO_SEND_TEXT_COLLECTION', 'sendtext')
MONGO_CHECK_STATUS_COLLECTION = os.getenv('MONGO_CHECK_STATUS_COLLECTION', 'check_status')
MONGO_COMMENT_COLLECTION = os.getenv('MONGO_COMMENT_COLLECTION', 'sendtext')


DEFAULT_SOCKET_TIMEOUT = 30
RECONNECT_DELAY = 2
SUCCESS_SEND_INTERVAL = 7200
FAILURE_COOLDOWN_INTERVAL = 86400
FIRST_FAILURE_COOLDOWN_INTERVAL = int(os.getenv('FIRST_FAILURE_COOLDOWN_INTERVAL', '15'))
FAILURE_COOLDOWN_30_DAYS = 2592001
INITIAL_MESSAGE_DELAY = 8
USER_ID_POLLING_INTERVAL = 60
USER_POLLING_INTERVAL = 60
MAX_RETRY_ATTEMPTS = 2
MAX_DAILY_USAGE = 2
TASK_INTERVAL = 30


SEND_MODE_CARD_ONLY = 1
SEND_MODE_TEXT_ONLY = 2
SEND_MODE_CARD_AND_TEXT = 3
SEND_MODE_CARD2_ONLY = 4
MESSAGE_SEND_MODE = 2
CARD_AND_TEXT_CARD = 1


CHECK_USER_ID = os.getenv('CHECK_USER_ID', '')
